server:
    port: 8082
spring:
    application:
        name: Department-Service
    datasource:
        driverClass: org.h2.Driver
        password: password
        url: jdbc:h2:mem:rmapp
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect