server:
  port: 8082

spring:
  application:
    name: Department-Service
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:mem:rmapp'
    driverClass: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect